# Generated by Django 5.0.4 on 2024-10-30 07:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="users",
            field=models.ManyToManyField(
                related_name="group_set",
                through="users.Membership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
